version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on: 
      - "mongo"
  mongo:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "27017:27017"